## Builder Image
FROM golang:1.13-stretch as builder
ENV GO111MODULE=on
COPY . /calculator
WORKDIR /calculator
RUN go get github.com/google/wire/cmd/wire
RUN wire ./...
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/application cmd/http/main.go cmd/http/wire_gen.go

## Run Image
FROM scratch
COPY --from=builder /calculator/bin/application application
EXPOSE 8080
ENTRYPOINT ["./application"]