// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Request) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type Reply struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceInCents         int32     `protobuf:"varint,4,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	Discount             *Discount `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Reply) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Reply) GetPriceInCents() int32 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func (m *Reply) GetDiscount() *Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

type Discount struct {
	Percentage           int32    `protobuf:"varint,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	ValueInCents         int32    `protobuf:"varint,2,opt,name=value_in_cents,json=valueInCents,proto3" json:"value_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{2}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetPercentage() int32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Discount) GetValueInCents() int32 {
	if m != nil {
		return m.ValueInCents
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "grpc.Request")
	proto.RegisterType((*Reply)(nil), "grpc.Reply")
	proto.RegisterType((*Discount)(nil), "grpc.Discount")
}

func init() {
	proto.RegisterFile("calculator.proto", fileDescriptor_c686ea360062a8cf)
}

var fileDescriptor_c686ea360062a8cf = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x6d, 0x9d, 0xce, 0xcf, 0xad, 0x16, 0x09, 0x82, 0x45, 0x50, 0x86, 0xe2, 0x42, 0x5c,
	0x74, 0x31, 0x6e, 0xdc, 0xca, 0xb8, 0xe9, 0x4e, 0xf2, 0x02, 0xa5, 0x26, 0x97, 0x21, 0x50, 0xda,
	0x98, 0x1f, 0xc1, 0xc7, 0xf1, 0x4d, 0x4d, 0xd2, 0x4c, 0xe9, 0xae, 0xe7, 0x3b, 0xbd, 0x39, 0xf7,
	0x1e, 0xb8, 0x61, 0x5d, 0xcf, 0x6c, 0xdf, 0x99, 0x51, 0xd5, 0x52, 0x8d, 0x66, 0x24, 0xab, 0x93,
	0x92, 0xac, 0x7a, 0x87, 0x0d, 0xc5, 0x6f, 0x8b, 0xda, 0x90, 0x3b, 0xd8, 0x58, 0x8d, 0xaa, 0x15,
	0xbc, 0x4c, 0xf6, 0xc9, 0xf3, 0x8e, 0xae, 0xbd, 0x6c, 0x38, 0x79, 0x00, 0x70, 0x23, 0xdc, 0x32,
	0xe3, 0xbd, 0x34, 0x78, 0xbb, 0x48, 0x1a, 0x5e, 0xfd, 0x25, 0x90, 0x51, 0x94, 0xfd, 0x2f, 0x29,
	0x20, 0x9d, 0x87, 0xdd, 0x17, 0xb9, 0x85, 0xcc, 0x08, 0xd3, 0x63, 0x9c, 0x99, 0x04, 0xd9, 0x43,
	0xce, 0x51, 0x33, 0x25, 0xa4, 0x11, 0xe3, 0x50, 0x5e, 0x06, 0x6f, 0x89, 0xc8, 0x13, 0x14, 0x52,
	0x09, 0x86, 0xad, 0x18, 0x5a, 0x86, 0x83, 0xd1, 0xe5, 0xca, 0xfd, 0x94, 0xd1, 0xab, 0x40, 0x9b,
	0xe1, 0xe8, 0x19, 0x79, 0x81, 0x2d, 0x17, 0x9a, 0x8d, 0x76, 0x30, 0x65, 0xe6, 0xfc, 0xfc, 0x50,
	0xd4, 0xfe, 0xa6, 0xfa, 0x23, 0x52, 0x3a, 0xfb, 0xd5, 0x27, 0x6c, 0xcf, 0x94, 0x3c, 0xba, 0x73,
	0x50, 0xf9, 0x77, 0xbb, 0x13, 0x86, 0x6d, 0x33, 0xba, 0x20, 0x3e, 0xfd, 0xa7, 0xeb, 0xed, 0x22,
	0x3d, 0x9d, 0xd2, 0x03, 0x8d, 0xe9, 0x87, 0x37, 0x80, 0xe3, 0x5c, 0xa9, 0xdb, 0x65, 0xa9, 0xae,
	0xa7, 0x3d, 0x62, 0xb1, 0xf7, 0xf9, 0x59, 0xba, 0x8e, 0xaa, 0x8b, 0xaf, 0x75, 0xe8, 0xff, 0xf5,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xe9, 0xb7, 0xf5, 0x93, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorClient interface {
	Calculator(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Calculator(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/grpc.Calculator/Calculator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServer is the server API for Calculator service.
type CalculatorServer interface {
	Calculator(context.Context, *Request) (*Reply, error)
}

// UnimplementedCalculatorServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (*UnimplementedCalculatorServer) Calculator(ctx context.Context, req *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculator not implemented")
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Calculator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Calculator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Calculator/Calculator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Calculator(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculator",
			Handler:    _Calculator_Calculator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator.proto",
}
